// This class is responsible for using the ho solver to calculate parameters for the
// lo order solver and setting those in the LO system via the mesh that is passed in
// (currently lo order data is stored on each mesh).  Ho Solver can compute the half
// range fluxes.  


//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : DataTransfer.cpp
//  @ Date : 2/7/2014
//  @ Author : 
//
//


#include "DataTransfer.h"
#include <iostream>

DataTransfer::DataTransfer(HoSolver* ho_solver, Mesh* mesh):
_ho_solver(ho_solver),
_mesh(mesh)
{}

void DataTransfer::updateLoSystem()
{
	//Loop over elements in the mesh
	Element* current_element;
	LoData1D lo_data;
	
	for (int el = 0; el < _mesh->getNumElems(); ++el)
	{
		current_element = _mesh->getElement(el);
		calculateLoData(lo_data, el);
		current_element->setLoData(lo_data);
	}
}

void DataTransfer::calculateLoData(LoData1D & lo_data, int element_id)
{
	//Currently it is teh responsibility of the ho solver to calculate the
	//lo data.  Eventually this could be changed by virtual overriding this
	//function for differnet dimensions.  This is currently a fairly pointless
	//class.

	_ho_solver->getLoData1D(lo_data, element_id);
} 
