//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ECMCTally.cpp
//  @ Date : 2/10/2014
//  @ Author : 
//
//


#include "ECMCTally.h"


ECMCTally::ECMCTally() : _angular_moment(1, 1), _spatial_moments(1,2)
{}




