//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ECMCElement.h
//  @ Date : 2/10/2014
//  @ Author : 
//
//


#if !defined(_ECMCELEMENT_H)
#define _ECMCELEMENT_H

#include "ECMCTally.h"
#include "Element.h"

class ECMCElement
{
protected:

	std::vector<double> _ang_flux_dof;  //The moments that are needed to reconstruct the angular flux
	ECMCTally* _tally;					//Tally that is used to compute the error each time
	std::vector<double> _coordinates;	//The center of the cell in terms of x,y,mu, mu is always last
	std::vector<double> _dimensions;	//Width of the cell in x,y,mu, mu is always last
	Element* _spatial_element; //The element in the LO geometry that this ECMC element points to
	ECMCElement();	//do not use 

public:

	//Constructors
	ECMCElement(Element* spatial_element, std::vector<double> dimensions, std::vector<double> coordinates);
	ECMCElement(Element* spatial_element, int number_spatial_dimensions, int number_angular_dimensions);  //let derived classes set actual values

	//Access functions
	std::vector<double> getElementDimensions() const;
	Element* getSpatialElement() const
	{
		return _spatial_element;
	}

};

#endif  //_ECMCELEMENT_H
