//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ECMCTally.h
//  @ Date : 2/10/2014
//  @ Author : 
//
//


#if !defined(_ECMCTALLY_H)
#define _ECMCTALLY_H

#include "CurrentElementTally.h"
#include "FluxElementTally.h"

class ECMCTally
{
protected:
	CurrentElementTally _angular_moment;
	FluxElementTally _spatial_moments;
public:
	ECMCTally(); //default constructor, will initialize the spatial moments
	void incrementScores(double weight, double path_length, double normalized_dir_cosine, 
		double volume, double normalized_position); //Using a normalized dir_cosine produces an always positive value for moment
};

#endif  //_ECMCTALLY_H
