//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  High Order Solver
//  @ File Name : ElementTally.h
//  @ Date : 1/27/2014
//  @ Author : Simon R Bolding
//
//


#if !defined(_ELEMENTTALLY_H)
#define _ELEMENTTALLY_H

#include "Tally.h"

class ElementTally : public Tally
{
public:
	virtual void incrementScore();
};

#endif  //_ELEMENTTALLY_H
