//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  High Order Solver
//  @ File Name : FaceTally.h
//  @ Date : 1/27/2014
//  @ Author : Simon R Bolding
//
//


#if !defined(_FACETALLY_H)
#define _FACETALLY_H

#include "Tally.h"

class FaceTally : public Tally
{
public:
	virtual void incrementScore();
	FaceTally();
};

#endif  //_FACETALLY_H
