//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  High Order Solver
//  @ File Name : FaceTally.cpp
//  @ Date : 1/27/2014
//  @ Author : Simon R Bolding
//
//


#include "FaceTally.h"

void FaceTally::incrementScore()
{

}

FaceTally::FaceTally() : Tally()
{

}