// 
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : HoMesh.h
//  @ Date : 2/10/2014
//  @ Author : srb
//
//
//  IF YOU WANT TO USE COORDINATES: This mesh always assumes that the x coordinate starts at 0.0 and then goes out from there.  
//  This is fine for 1D, but in multi-D you would need to have a lo_mesh.getNodes() function 
//  to determine the center of each cell, etc.
//


#if !defined(_HOMESH_H)
#define _HOMESH_H

#include "ECMCElement.h"
#include "ECMCElement1D.h"
#include "Mesh.h"


class HoMesh
{
protected:
	std::vector<ECMCElement*> _elements;
	int _n_elems;
	HoMesh(); //don't use
public:
	HoMesh(Mesh* mesh, int n_ang_cells_half_range); //how much to divide the angular cells into
	ECMCElement* getElement(int element_id) const;
	int getNumElems() const;
	std::vector<ECMCElement* >* getElements(void);
};

#endif  //_HOMESH_H
