//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : HoMesh.cpp
//  @ Date : 2/10/2014
//  @ Author : 
//
//


#include "HoMesh.h"

HoMesh::HoMesh(Mesh* lo_mesh, int n_ang_cells_half_range)
{
	//Local variables
	std::vector<Element*>* spatial_elements;
	spatial_elements = lo_mesh->getElements();
	std::vector<Element*>::iterator it_el;          //element iterator
	it_el = spatial_elements->begin();
	
	//Loop over the lo mesh elements
	for (; it_el != spatial_elements->end(); it_el++)
	{
		std::cout << "cool" << std::endl;
	}

}

ECMCElement* HoMesh::getElement(int element_id) const
{
	return _elements[element_id];
}

int HoMesh::getNumElems() const
{
	return _n_elems;
}

std::vector<ECMCElement* >* HoMesh::getElements(void)
{
	return &_elements; //pointer, be careful not to change these values
}
