// 
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : MaterialConstant.cpp
//  @ Date : 11/3/2013
//  @ Author : @SRB
//
//


#include "MaterialConstant.h"
#include <iomanip>

MaterialConstant::MaterialConstant()
{
	//Never call me
}

MaterialConstant::MaterialConstant(int id, double sigma_a, double sigma_s)
{
	_id = id;
	_sigma_a = sigma_a;
	_sigma_s = sigma_s;
	_sigma_t = _sigma_a + _sigma_s;
}

double MaterialConstant::getSigmaA( void) const
{
	return _sigma_a;
}

double MaterialConstant::getSigmaT( void) const
{
	return _sigma_t;
}

double MaterialConstant::getSigmaS( void) const
{
	return _sigma_s;
}

int MaterialConstant::getID(void) const
{
	return _id;
}

void MaterialConstant::print(std::ostream &out) const
{
	using std::endl;
	out << " ID = ";
	out.width(4);
	out << _id;
	out << ", sig_a = ";
	std::setprecision(4);
	out << _sigma_a;
	out << ", sig_s = ";
	std::setprecision(4);
	out << _sigma_s;
	out << ", sig_t = ";
	std::setprecision(4);
	out << _sigma_t << endl;
}
