// Currently all materials are constants in space. TODO make it so materials have a
// name and not just an ID #.
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : MaterialConstant.h
//  @ Date : 11/3/2013
//  @ Author : SRB
//
//


#ifndef _MATERIALCONSTANT_H
#define _MATERIALCONSTANT_H

#include <ostream>

class MaterialConstant
{
protected:
    double _sigma_a;		//Absorption
    double _sigma_s;		//Scattering
    double _sigma_t;		//Total
    int _id;			//Material ID

public:
	MaterialConstant();	//Default Constructor, may be used
	MaterialConstant(int id, double sigma_a, double sigma_s);
    double getSigmaS(void) const;
    double getSigmaT(void) const;
    double getSigmaA(void) const;
    int getID(void) const;
	void print(std::ostream &out) const;
};

#endif  //_MATERIALCONSTANT_H
