//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  High Order Solver
//  @ File Name : Particle1D.h
//  @ Date : 1/27/2014
//  @ Author : Simon R Bolding
//
//


#if !defined(_PARTICLE1D_H)
#define _PARTICLE1D_H


class Particle1D
{
protected:

	double _position;
	double _mu;
	int _current_element;
	double samplePathLength();
	void updatePosition(double path_length);

public:
	void streamThroughCell();
};

#endif  //_PARTICLE1D_H
