//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ResidualSource.h
//  @ Date : 2/8/2014
//  @ Author : 
//
//


#if !defined(_RESIDUALSOURCE_H)
#define _RESIDUALSOURCE_H

#include "Source.h"

class ResidualSource : public Source
{
public:
	virtual void sampleSourceParticle() = 0;
};

#endif  //_RESIDUALSOURCE_H
