//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  High Order Solver
//  @ File Name : Tally.cpp
//  @ Date : 1/27/2014
//  @ Author : Simon R Bolding
//
//


#include "Tally.h"

double Tally::getScore(int _n_histories)
{
	return 0;
}

Tally::Tally(int _n_angle_bins, int _n_spatial_moment_bins)
{

}

Tally::Tally()
{

}

